name: RESTUIT Auto Reply

on:
  schedule:
    - cron: '*/30 * * * *'  # Ejecutar cada 30 minutos
  workflow_dispatch:  # Permite ejecutar manualmente desde GitHub

jobs:
  reply_to_mentions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v4  # Actualiza a la última versión (v4)

    - name: Set up Python
      uses: actions/setup-python@v4  # Actualiza a la versión v4 de setup-python
      with:
        python-version: '3.x'  # Usar la versión más reciente de Python

    - name: Install dependencies
      run: |
        pip install tweepy  # Instalar Tweepy para usar la API de Twitter

    - name: Run RESTUIT script with logging
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: |
        python3 restuit_reply.py || echo "Error en la ejecución del script Python"
