name: RESTUIT Auto Reply

on:
  schedule:
    - cron: '*/30 * * * *'  # Ejecutar cada 30 minutos
  workflow_dispatch:  # Permite ejecutar manualmente desde GitHub

jobs:
  reply_to_mentions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3  # Actualiza a la última versión de la acción de checkout

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Usar la versión más reciente de Python

    - name: Setup Node.js  # Paso para actualizar Node.js si es necesario
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Usar la versión más reciente de Node.js (puedes ajustar según sea necesario)

    - name: Install dependencies
      run: |
        pip install tweepy  # Instalar Tweepy para usar la API de Twitter

    - name: Run RESTUIT script
      env:
        TWITTER_CONSUMER_KEY: 'tYEkW50YVJh767fIZjcFUy7iD'
        TWITTER_CONSUMER_SECRET: '3ABDOkjqWjFQCYzvNbZ9FtelSGfwPYS85XKR9gpfFj3HRtEaRC'
        TWITTER_ACCESS_TOKEN: '1445541467175337994-vH5ctinZJMkB4Nqsv4uTHNfx82DH4N'
        TWITTER_ACCESS_TOKEN_SECRET: 'jwLL8WrleRoo8IPSlDOqslDW2UJhsj5bEIWpSj7yT1HCi'
      run: |
        python3 restuit_reply.py
